version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: rnd-platform-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - rnd-platform-network

  mongo-express:
    image: mongo-express
    container_name: rnd-platform-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - rnd-platform-network

volumes:
  mongodb_data:

networks:
  rnd-platform-network:
    driver: bridge
