---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/server:TAG
          ports:
            - containerPort: 3000
          env:
            - name: PROD_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MongodbURIKey
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JwtKey
            - name: JWT_EXPIRATION
              value: "8h"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/client:TAG
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://server-service.ENVIRONMENT_NAMESPACE.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rnd-platform-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.global-static-ip-name: "STATIC_IP_NAME_PLACEHOLDER"
spec:
  tls:
    - hosts:
        - rndplatform.juriba.info
      secretName: rnd-platform-tls
  rules:
    - host: rndplatform.juriba.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MongodbURIKey: "MONGODB_URI_SECRET"
  JwtKey: "JWT_KEY_SECRET"
