export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const BLACKLISTED_TOKEN_REPOSITORY = Symbol('BLACKLISTED_TOKEN_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
